### ISSUE TITLE
Problems with client-secret

### ISSUE THREAD

**Issue by zahkruin** [codeaches/jwt-oauth2-and-resource-servers#1]
Hi, I'm trying to adapt this project to my app, but if I change the client-secret it doesn't works. In log it says "Encoded password does not look like BCrypt" only if the client-secret it's not the same that you give in the tutorial ($2a$08$ePUWmsLTqNezRk7MCUfg6.HU3RUO3N2M6H.Xj0gMvKiUsGgvg/Fve). Can you help me, please?
Thanks

#Edit:
I have the same issue with the users's passwords, if I change the passwords that you give, it doesn't works. In log it says "Encoded password does not look like BCrypt" and "Handling error: InvalidGrantException, Bad credentials" but I'm entering the correct one...

**Comment by zahkruin** [comment]
Hi again. I solved it. I don't know why, but the bcrypt generator i was using didn't use the rounds correctly. so I change it and now it works. I use https://www.browserling.com/tools/bcrypt now

**Comment by codeaches** [comment]
Glad to hear @zahkruin . You can view this tutorial if interested.
https://codeaches.com/blog/jwt-spring-security-oauth2-and-resource-server/
